# /tasks/apply.yml
---
- include_tasks: apply-{{ ansible_os_family }}.yml

- name: apply | add group
  group:
    name: "{{ docker_group }}"
    system: true
    state: present

- name: apply | add user to group
  user:
    name: "{{ ansible_env.USER }}"
    groups: "{{ docker_group }}"
    append: yes
  when: ansible_env.USER is defined

- name: apply | add sudo user to group
  user:
    name: "{{ ansible_env.SUDO_USER }}"
    groups: "{{ docker_group }}"
    append: yes
  when: ansible_env.SUDO_USER is defined

- name: apply | create folders
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker.log_dir }}"
    - "{{ docker.conf_dir }}"
