# docker/tasks/configure.yml
---
- name: configure | partition
  parted:
    device: "{{ docker_config_storage_device }}"
    number: "{{ docker_config_storage_device_number }}"
    flags:
    - lvm
    state: present

- name: configure | create volume group
  lvg:
    vg: "{{ docker_lvm_volume_group }}"
    pvs: "{{ docker_config_directlvm_device }}"
    state: present
    vg_options: "--zero y --force"
  register: create_volume_group

- name: configure | create logical volume
  lvol:
    vg: "{{ docker_lvm_volume_group }}"
    lv: thinpool
    size: "{{ docker_config_thinp_percent }}%VG"
    opts: "--wipesignatures y"
    force: yes
  register: create_logicial_volume

- name: configure | create logical meta volume
  lvol:
    vg: "{{ docker_lvm_volume_group }}"
    lv: thinpoolmeta
    size: "{{ docker_config_thinp_metapercent }}%VG"
    opts: "--wipesignatures y"
    force: yes
  register: create_logicial_meta_volume

- name: configure | convert to thinpool
  command: lvconvert -y --zero n -c 512K --thinpool {{ docker_lvm_volume_group }}/thinpool --poolmetadata {{ docker_lvm_volume_group }}/thinpoolmeta
  when:
    - create_volume_group.changed
    - create_logicial_volume.changed
    - create_logicial_meta_volume.changed

- name: configure | create lvm profile
  template:
    src: docker-thinpool.profile.j2
    dest: /etc/lvm/profile/docker-thinpool.profile
    mode: 0644
  register: docker_lvm_profile

- name: configure | apply lvm profile
  command: lvchange --metadataprofile docker-thinpool {{ docker_lvm_volume_group }}/thinpool
  when:
    - docker_lvm_profile.changed

- name: configure | daemon
  template:
    src: daemon.json.j2
    dest: "{{ docker.conf_dir }}/daemon.json"
  notify:
    - restart docker



#pvcreate /dev/sdb1 --force
#parted /dev/sdb
#vgcreate docker /dev/sdb1
#lvcreate --wipesignatures y -n thinpool docker -l 95%VG
#lvcreate --wipesignatures y -n thinpoolmeta docker -l 1%VG

#sudo lvconvert -y --zero n -c 512K --thinpool docker/thinpool --poolmetadata docker/thinpoolmeta
#sudo vi /etc/lvm/profile/docker-thinpool.profile

#lvchange --metadataprofile docker-thinpool docker/thinpool
#lvs -o+seg_monitor
#systemctl restart docker


