# docker/tasks/configure.yml
---
- parted:
    device: "{{ docker_config_storage_device }}"
    number: "{{ docker_config_storage_device_number }}"
    flags:
    - lvm
    state: present

- name: configure | daemon
  template:
    src: daemon.json.j2
    dest: "{{ docker.conf_dir }}/daemon.json"
  notify:
    - restart docker

#- name: configure | create vol group
#  lvg:
#    vg: vg.docker
#    pvs: "{{ docker_config_storage_device }}"
#    state: present
#
#- name: configure | create vol
#  lvol:
#    vg: vg.docker
#    lv: storage
#    size: "{{ docker_config_storage_ratio }}%VG"
#    thinpool: docker
#
#- name: configure | create vol meta
#  lvol:
#    vg: vg.docker
#    lv: storagemeta
#    size: "{{ docker_config_storage_ratio }}%VG"
#    thinpool: dockermeta


#sudo lvcreate --wipesignatures y -n thinpool docker -l 95%VG
#
#Logical volume "thinpool" created.
#
#$ sudo lvcreate --wipesignatures y -n thinpoolmeta docker -l 1%VG
#
#Logical volume "thinpoolmeta" created.
#
#Convert the volumes to a thin pool and a storage location for metadata for the thin pool, using the lvconvert command.
#
#$ sudo lvconvert -y \
#--zero n \
#-c 512K \
#--thinpool docker/thinpool \
#--poolmetadata docker/thinpoolmeta
#
#WARNING: Converting logical volume docker/thinpool and docker/thinpoolmeta to
#thin pool's data and metadata volumes with metadata wiping.
#THIS WILL DESTROY CONTENT OF LOGICAL VOLUME (filesystem etc.)
#Converted docker/thinpool to thin pool.



#    4  2018-01-30 05:12:39 lvcreate --wipesignatures y -n thinpool docker -l 95%VG
#    5  2018-01-30 05:12:41 lvcreate --wipesignatures y -n thinpoolmeta docker -l 1%VG
#    6  2018-01-30 05:12:49 lvconvert -y --zero n -c 512K --thinpool docker/thinpool --poolmetadata docker/thinpoolmeta
#    7  2018-01-30 05:13:13 cat <<'_EOF' >/etc/lvm/profile/docker-thinpool.profile
#activation {
#    thin_pool_autoextend_threshold=80
#    thin_pool_autoextend_percent=20
#}
#_EOF
#
#   27  2018-01-30 05:51:10 lvchange --metadataprofile docker-thinpool docker/thinpool
#   28  2018-01-30 05:51:34 lvs -o+seg_monitor
#   30  2018-01-30 05:52:17 rm -rf /var/lib/docker/*
#   31  2018-01-30 05:52:40 mv daemon.old daemon.json
#   32  2018-01-30 05:52:46 systemctl restart docker


#sudo vi /etc/lvm/profile/docker-thinpool.profile
#
#Specify thin_pool_autoextend_threshold and thin_pool_autoextend_percent values.
#
#thin_pool_autoextend_threshold is the percentage of space used before lvm attempts to autoextend the available space (100 = disabled, not recommended).
#
#thin_pool_autoextend_percent is the amount of space to add to the device when automatically extending (0 = disabled).
#
#The example below adds 20% more capacity when the disk usage reaches 80%.
#
#activation {
#  thin_pool_autoextend_threshold=80
#  thin_pool_autoextend_percent=20
#}

#
#sudo lvchange --metadataprofile docker-thinpool docker/thinpool
#
#lvs -o+seg_monitor